apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-helloworld-server
  namespace: dev
spec:
  selector:
    matchLabels:
      app: grpc-helloworld-server
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-helloworld-server
    spec:
      containers:
      - name: grpc-helloworld-server
        image: "woodsmur/grpc-examples-helloworld-server"
        resources:
          limits:
            cpu: 64m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
